sudo: required
services:
  - docker

before_install:
  - docker build -t dhanasekars/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true dhanasekars/react-test npm test

after_success: 
  - docker build -t dhanasekars/multi-client ./client
  - docker build -t dhanasekars/multi-nginx ./nginx 
  - docker build -t dhanasekars/multi-server ./server 
  - docker build -t dhanasekars/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKERPWD" | docker login -u "$DOCKERID" --password-stdin

# Take the image and push to docker. 
  - docker push dhanasekars/multi-client
  - docker push dhanasekars/multi-nginx
  - docker push dhanasekars/multi-server
  - docker push dhanasekars/multi-worker